### 1️⃣ Register a New Tenant + Owner
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "tenantName": "Belfeki Dev",
    "name": "omar belfeki",
    "email": "omar@b.com",
    "password": "password123"
}

### 2️⃣ Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "omar@b.com",
    "password": "password123"
}

### 3️⃣ Create a Project (Owner/Admin Only)
POST http://localhost:5000/api/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OTA2MTE3NjkzOGQ1NWNlNjNjNzQxYyIsImlhdCI6MTc1NDI5MzA5OSwiZXhwIjoxNzU0ODk3ODk5fQ.QG9cIAfo4EaqsXmq1dtSNFUcvKdO9ThUgxO2LwI5tPs
Content-Type: application/json

{
    "name": "New SaaS Platform",
    "description": "Backend for multi-tenant application"
}


### 4️⃣ Get All Projects for Tenant
GET http://localhost:5000/api/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OTA2MTE3NjkzOGQ1NWNlNjNjNzQxYyIsImlhdCI6MTc1NDI5MzA5OSwiZXhwIjoxNzU0ODk3ODk5fQ.QG9cIAfo4EaqsXmq1dtSNFUcvKdO9ThUgxO2LwI5tPs